// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocieayhwtvjhwdezkesm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jaWVheWh3dHZqaHdkZXprZXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNjk4OTUsImV4cCI6MjA4NDk0NTg5NX0.Ad0ovIJKFz_n78rjUSO7UMMvFnqxuy6DIs-uJhzQkZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});